-- Approved logical-game migration.
-- Adds logical My9BGM games which can own multiple provider game IDs.

begin;

create table if not exists public.game_external_ids (
  id bigint generated by default as identity primary key,
  game_id bigint not null references public.games(id) on delete restrict,
  provider text not null check (provider in ('igdb', 'rawg')),
  external_id bigint not null check (external_id > 0),
  created_at timestamptz not null default now(),
  constraint game_external_ids_provider_external_id_key unique (provider, external_id)
);

create index if not exists game_external_ids_game_id_idx
  on public.game_external_ids (game_id);

alter table public.game_external_ids enable row level security;

grant select on public.game_external_ids to anon, authenticated;

do $policy$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'game_external_ids'
      and policyname = 'game_external_ids_public_read'
  ) then
    create policy game_external_ids_public_read
      on public.game_external_ids
      for select
      to anon, authenticated
      using (true);
  end if;
end
$policy$;

alter table public.bgms
  add column if not exists game_id bigint references public.games(id) on delete restrict;

create index if not exists bgms_game_id_idx
  on public.bgms (game_id);

create unique index if not exists bgms_game_id_normalized_title_key
  on public.bgms (game_id, normalized_title)
  where game_id is not null;

comment on table public.game_external_ids is
  'Provider IDs which resolve to one logical My9BGM game.';
comment on column public.bgms.game_id is
  'Logical My9BGM game. Nullable for backward compatibility with existing provider-ID rows.';

-- A cover is presentation metadata only. It does not designate a primary IGDB ID.
with desired(name, normalized_name, image_url, released) as (
  values
    ('ポケモン不思議のダンジョン 時の探検隊・闇の探検隊', 'ポケモン不思議のダンジョン時の探検隊闇の探検隊', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1yzu.jpg', '2007-09-13'),
    ('ポケットモンスター スカーレット・バイオレット', 'ポケットモンスタースカーレットバイオレット', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co5shr.jpg', '2022-11-18'),
    ('ポケットモンスター 赤・緑', 'ポケットモンスター赤緑', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co5pi4.jpg', '1996-02-27'),
    ('ポケットモンスター 金・銀', 'ポケットモンスター金銀', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co5pia.jpg', '1999-11-21'),
    ('ポケットモンスター ルビー・サファイア', 'ポケットモンスタールビーサファイア', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1zhq.jpg', '2002-11-21'),
    ('ポケットモンスター ダイヤモンド・パール', 'ポケットモンスターダイヤモンドパール', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1zht.jpg', '2006-09-28'),
    ('ポケットモンスター ブラック・ホワイト', 'ポケットモンスターブラックホワイト', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1z1x.jpg', '2010-09-18'),
    ('ポケットモンスター X・Y', 'ポケットモンスターxy', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1z8y.jpg', '2013-10-12'),
    ('ポケットモンスター サン・ムーン', 'ポケットモンスターサンムーン', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co3co7.jpg', '2016-11-18'),
    ('ポケットモンスター ソード・シールド', 'ポケットモンスターソードシールド', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co2lj2.jpg', '2019-11-15'),
    ('ポケモン不思議のダンジョン 青の救助隊・赤の救助隊', 'ポケモン不思議のダンジョン青の救助隊赤の救助隊', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1yyk.jpg', '2005-11-17'),
    ('FINAL FANTASY VI', 'finalfantasyvi', 'https://images.igdb.com/igdb/image/upload/t_cover_big/coaq5k.jpg', '1994-04-02')
)
insert into public.games (
  rawg_game_id,
  igdb_game_id,
  name,
  normalized_name,
  image_url,
  released
)
select null, null, d.name, d.normalized_name, d.image_url, d.released::date
from desired d
where not exists (
  select 1 from public.games g where g.normalized_name = d.normalized_name
);

-- Refuse to reuse a pre-existing normalized-name collision as another logical game.
do $guard$
begin
  if exists (
    with desired(name, normalized_name) as (
      values
        ('ポケモン不思議のダンジョン 時の探検隊・闇の探検隊', 'ポケモン不思議のダンジョン時の探検隊闇の探検隊'),
        ('ポケットモンスター スカーレット・バイオレット', 'ポケットモンスタースカーレットバイオレット'),
        ('ポケットモンスター 赤・緑', 'ポケットモンスター赤緑'),
        ('ポケットモンスター 金・銀', 'ポケットモンスター金銀'),
        ('ポケットモンスター ルビー・サファイア', 'ポケットモンスタールビーサファイア'),
        ('ポケットモンスター ダイヤモンド・パール', 'ポケットモンスターダイヤモンドパール'),
        ('ポケットモンスター ブラック・ホワイト', 'ポケットモンスターブラックホワイト'),
        ('ポケットモンスター X・Y', 'ポケットモンスターxy'),
        ('ポケットモンスター サン・ムーン', 'ポケットモンスターサンムーン'),
        ('ポケットモンスター ソード・シールド', 'ポケットモンスターソードシールド'),
        ('ポケモン不思議のダンジョン 青の救助隊・赤の救助隊', 'ポケモン不思議のダンジョン青の救助隊赤の救助隊'),
        ('FINAL FANTASY VI', 'finalfantasyvi')
    )
    select 1
    from desired d
    left join public.games g on g.normalized_name = d.normalized_name
    where g.id is null or g.name <> d.name
  ) then
    raise exception 'Logical game insertion failed or a normalized-name collision exists';
  end if;
end
$guard$;

with desired(normalized_name, provider, external_id) as (
  values
    ('ポケモン不思議のダンジョン時の探検隊闇の探検隊', 'igdb', 2321::bigint),
    ('ポケモン不思議のダンジョン時の探検隊闇の探検隊', 'igdb', 2322::bigint),
    ('ポケットモンスタースカーレットバイオレット', 'igdb', 191931::bigint),
    ('ポケットモンスタースカーレットバイオレット', 'igdb', 191930::bigint),
    ('ポケットモンスター赤緑', 'igdb', 1561::bigint),
    ('ポケットモンスター赤緑', 'igdb', 1511::bigint),
    ('ポケットモンスター金銀', 'igdb', 1558::bigint),
    ('ポケットモンスター金銀', 'igdb', 1513::bigint),
    ('ポケットモンスタールビーサファイア', 'igdb', 1557::bigint),
    ('ポケットモンスタールビーサファイア', 'igdb', 1515::bigint),
    ('ポケットモンスターダイヤモンドパール', 'igdb', 1560::bigint),
    ('ポケットモンスターダイヤモンドパール', 'igdb', 1518::bigint),
    ('ポケットモンスターブラックホワイト', 'igdb', 1521::bigint),
    ('ポケットモンスターブラックホワイト', 'igdb', 1522::bigint),
    ('ポケットモンスターxy', 'igdb', 2286::bigint),
    ('ポケットモンスターxy', 'igdb', 2287::bigint),
    ('ポケットモンスターサンムーン', 'igdb', 18100::bigint),
    ('ポケットモンスターサンムーン', 'igdb', 18099::bigint),
    ('ポケットモンスターソードシールド', 'igdb', 37382::bigint),
    ('ポケットモンスターソードシールド', 'igdb', 115653::bigint),
    ('ポケモン不思議のダンジョン青の救助隊赤の救助隊', 'igdb', 2320::bigint),
    ('ポケモン不思議のダンジョン青の救助隊赤の救助隊', 'igdb', 2319::bigint),
    ('finalfantasyvi', 'igdb', 426::bigint)
)
insert into public.game_external_ids (game_id, provider, external_id)
select g.id, d.provider, d.external_id
from desired d
join public.games g on g.normalized_name = d.normalized_name
on conflict (provider, external_id) do nothing;

-- Any provider-ID collision rolls the whole transaction back instead of reassigning it.
do $guard$
begin
  if exists (
    with desired(normalized_name, provider, external_id) as (
      values
        ('ポケモン不思議のダンジョン時の探検隊闇の探検隊', 'igdb', 2321::bigint),
        ('ポケモン不思議のダンジョン時の探検隊闇の探検隊', 'igdb', 2322::bigint),
        ('ポケットモンスタースカーレットバイオレット', 'igdb', 191931::bigint),
        ('ポケットモンスタースカーレットバイオレット', 'igdb', 191930::bigint),
        ('ポケットモンスター赤緑', 'igdb', 1561::bigint),
        ('ポケットモンスター赤緑', 'igdb', 1511::bigint),
        ('ポケットモンスター金銀', 'igdb', 1558::bigint),
        ('ポケットモンスター金銀', 'igdb', 1513::bigint),
        ('ポケットモンスタールビーサファイア', 'igdb', 1557::bigint),
        ('ポケットモンスタールビーサファイア', 'igdb', 1515::bigint),
        ('ポケットモンスターダイヤモンドパール', 'igdb', 1560::bigint),
        ('ポケットモンスターダイヤモンドパール', 'igdb', 1518::bigint),
        ('ポケットモンスターブラックホワイト', 'igdb', 1521::bigint),
        ('ポケットモンスターブラックホワイト', 'igdb', 1522::bigint),
        ('ポケットモンスターxy', 'igdb', 2286::bigint),
        ('ポケットモンスターxy', 'igdb', 2287::bigint),
        ('ポケットモンスターサンムーン', 'igdb', 18100::bigint),
        ('ポケットモンスターサンムーン', 'igdb', 18099::bigint),
        ('ポケットモンスターソードシールド', 'igdb', 37382::bigint),
        ('ポケットモンスターソードシールド', 'igdb', 115653::bigint),
        ('ポケモン不思議のダンジョン青の救助隊赤の救助隊', 'igdb', 2320::bigint),
        ('ポケモン不思議のダンジョン青の救助隊赤の救助隊', 'igdb', 2319::bigint),
        ('finalfantasyvi', 'igdb', 426::bigint)
    )
    select 1
    from desired d
    join public.games g on g.normalized_name = d.normalized_name
    left join public.game_external_ids e
      on e.provider = d.provider and e.external_id = d.external_id
    where e.game_id is distinct from g.id
  ) then
    raise exception 'An external game ID is already assigned to another logical game';
  end if;
end
$guard$;

with desired(game_normalized_name, alias, normalized_alias) as (
  values
    ('ポケモン不思議のダンジョン時の探検隊闇の探検隊', 'ポケモン不思議のダンジョン 時の探検隊・闇の探検隊', 'ポケモン不思議のダンジョン時の探検隊闇の探検隊'),
    ('ポケモン不思議のダンジョン時の探検隊闇の探検隊', 'Pokémon Mystery Dungeon: Explorers of Time', 'pokemonmysterydungeonexplorersoftime'),
    ('ポケモン不思議のダンジョン時の探検隊闇の探検隊', 'Pokémon Mystery Dungeon: Explorers of Darkness', 'pokemonmysterydungeonexplorersofdarkness'),
    ('ポケットモンスタースカーレットバイオレット', 'ポケットモンスター スカーレット・バイオレット', 'ポケットモンスタースカーレットバイオレット'),
    ('ポケットモンスタースカーレットバイオレット', 'ポケモン スカーレット', 'pokemonスカーレット'),
    ('ポケットモンスタースカーレットバイオレット', 'ポケモン バイオレット', 'pokemonバイオレット'),
    ('ポケットモンスタースカーレットバイオレット', 'Pokémon Scarlet', 'pokemonscarlet'),
    ('ポケットモンスタースカーレットバイオレット', 'Pokémon Violet', 'pokemonviolet'),
    ('ポケットモンスター赤緑', 'ポケットモンスター 赤・緑', 'ポケットモンスター赤緑'),
    ('ポケットモンスター赤緑', 'ポケモン 赤', 'pokemon赤'),
    ('ポケットモンスター赤緑', 'ポケモン 緑', 'pokemon緑'),
    ('ポケットモンスター赤緑', 'Pokémon Red Version', 'pokemonredversion'),
    ('ポケットモンスター赤緑', 'Pocket Monsters Green', 'pocketmonstersgreen'),
    ('ポケットモンスター赤緑', 'Pokémon Green Version', 'pokemongreenversion'),
    ('ポケットモンスター金銀', 'ポケットモンスター 金・銀', 'ポケットモンスター金銀'),
    ('ポケットモンスター金銀', 'ポケモン 金', 'pokemongold'),
    ('ポケットモンスター金銀', 'ポケモン 銀', 'pokemonsilver'),
    ('ポケットモンスター金銀', 'Pokémon Gold Version', 'pokemongoldversion'),
    ('ポケットモンスター金銀', 'Pokémon Silver Version', 'pokemonsilverversion'),
    ('ポケットモンスタールビーサファイア', 'ポケットモンスター ルビー・サファイア', 'ポケットモンスタールビーサファイア'),
    ('ポケットモンスタールビーサファイア', 'ポケモン ルビー', 'pokemonルビー'),
    ('ポケットモンスタールビーサファイア', 'ポケモン サファイア', 'pokemonサファイア'),
    ('ポケットモンスタールビーサファイア', 'Pokémon Ruby Version', 'pokemonrubyversion'),
    ('ポケットモンスタールビーサファイア', 'Pokémon Sapphire Version', 'pokemonsapphireversion'),
    ('ポケットモンスターダイヤモンドパール', 'ポケットモンスター ダイヤモンド・パール', 'ポケットモンスターダイヤモンドパール'),
    ('ポケットモンスターダイヤモンドパール', 'ポケモン ダイヤモンド', 'pokemondiamond'),
    ('ポケットモンスターダイヤモンドパール', 'ポケモン パール', 'pokemonpearl'),
    ('ポケットモンスターダイヤモンドパール', 'Pokémon Diamond Version', 'pokemondiamondversion'),
    ('ポケットモンスターダイヤモンドパール', 'Pokémon Pearl Version', 'pokemonpearlversion'),
    ('ポケットモンスターブラックホワイト', 'ポケットモンスター ブラック・ホワイト', 'ポケットモンスターブラックホワイト'),
    ('ポケットモンスターブラックホワイト', 'ポケモン ブラック', 'pokemonblack'),
    ('ポケットモンスターブラックホワイト', 'ポケモン ホワイト', 'pokemonwhite'),
    ('ポケットモンスターブラックホワイト', 'Pokémon Black Version', 'pokemonblackversion'),
    ('ポケットモンスターブラックホワイト', 'Pokémon White Version', 'pokemonwhiteversion'),
    ('ポケットモンスターxy', 'ポケットモンスター X・Y', 'ポケットモンスターxy'),
    ('ポケットモンスターxy', 'Pokémon X', 'pokemonx'),
    ('ポケットモンスターxy', 'Pokémon Y', 'pokemony'),
    ('ポケットモンスターサンムーン', 'ポケットモンスター サン・ムーン', 'ポケットモンスターサンムーン'),
    ('ポケットモンスターサンムーン', 'ポケモン サン', 'pokemonサン'),
    ('ポケットモンスターサンムーン', 'ポケモン ムーン', 'pokemonムーン'),
    ('ポケットモンスターサンムーン', 'Pokémon Sun', 'pokemonsun'),
    ('ポケットモンスターサンムーン', 'Pokémon Moon', 'pokemonmoon'),
    ('ポケットモンスターソードシールド', 'ポケットモンスター ソード・シールド', 'ポケットモンスターソードシールド'),
    ('ポケットモンスターソードシールド', 'ポケモン ソード', 'pokemonソード'),
    ('ポケットモンスターソードシールド', 'ポケモン シールド', 'pokemonシールド'),
    ('ポケットモンスターソードシールド', 'Pokémon Sword', 'pokemonsword'),
    ('ポケットモンスターソードシールド', 'Pokémon Shield', 'pokemonshield'),
    ('ポケモン不思議のダンジョン青の救助隊赤の救助隊', 'ポケモン不思議のダンジョン 青の救助隊・赤の救助隊', 'ポケモン不思議のダンジョン青の救助隊赤の救助隊'),
    ('ポケモン不思議のダンジョン青の救助隊赤の救助隊', 'Pokémon Mystery Dungeon: Blue Rescue Team', 'pokemonmysterydungeonbluerescueteam'),
    ('ポケモン不思議のダンジョン青の救助隊赤の救助隊', 'Pokémon Mystery Dungeon: Red Rescue Team', 'pokemonmysterydungeonredrescueteam'),
    ('finalfantasyvi', 'FINAL FANTASY VI', 'finalfantasyvi'),
    ('finalfantasyvi', 'FFVI', 'ffvi'),
    ('finalfantasyvi', 'ファイナルファンタジーVI', 'ファイナルファンタジーvi')
)
insert into public.game_aliases (game_id, alias, normalized_alias, source)
select g.id, d.alias, d.normalized_alias, 'logical-game'
from desired d
join public.games g on g.normalized_name = d.game_normalized_name
where not exists (
  select 1
  from public.game_aliases a
  where a.game_id = g.id and a.normalized_alias = d.normalized_alias
);

commit;

-- Post-apply verification (read-only): expected 12 logical games and 23 IGDB mappings.
select count(*) as logical_game_count
from public.games
where normalized_name in (
  'ポケモン不思議のダンジョン時の探検隊闇の探検隊',
  'ポケットモンスタースカーレットバイオレット',
  'ポケットモンスター赤緑',
  'ポケットモンスター金銀',
  'ポケットモンスタールビーサファイア',
  'ポケットモンスターダイヤモンドパール',
  'ポケットモンスターブラックホワイト',
  'ポケットモンスターxy',
  'ポケットモンスターサンムーン',
  'ポケットモンスターソードシールド',
  'ポケモン不思議のダンジョン青の救助隊赤の救助隊',
  'finalfantasyvi'
);

select count(*) as igdb_mapping_count
from public.game_external_ids
where provider = 'igdb'
  and external_id in (
    2321, 2322, 191931, 191930, 1561, 1511, 1558, 1513,
    1557, 1515, 1560, 1518, 1521, 1522, 2286, 2287,
    18100, 18099, 37382, 115653, 2320, 2319, 426
  );
